//! Typed query helpers built on the active driver.
//!
//! Records implementing [`DbRecord`] expose a typed select query and column
//! handles that the driver's [`query`](crate::connection::DbDriver::query),
//! [`insert`](crate::connection::DbDriver::insert), and
//! [`delete`](crate::connection::DbDriver::delete) helpers consume.
//!
//! `#[derive(DbRecord)]` (provided by `suon_macros`) generates these impls
//! together with the Diesel `table!`, `Queryable`, `Selectable`, and
//! `Insertable` glue.

use std::marker::PhantomData;

use anyhow::Result;
use diesel::{
    Connection, Insertable, RunQueryDsl,
    associations::HasTable,
    expression::Expression,
    insertable::CanInsertInSingleQuery,
    query_builder::{QueryFragment, QueryId},
    query_dsl::{
        LoadQuery,
        methods::{ExecuteDsl, FilterDsl, OrderDsl},
    },
};

use crate::connection::DbDriver;

/// Database record metadata generated by `#[derive(DbRecord)]`.
pub trait DbRecord: HasTable {
    /// Typed select query for this record.
    type Query;
    /// Typed table column handles exposed to query closures.
    type Columns;

    /// Builds a typed select query.
    fn query() -> Self::Query;
    /// Builds typed table column handles.
    fn columns() -> Self::Columns;
}

/// Pending query or write operation captured by the driver.
pub struct PendingStatement<'driver, Query, Record = ()> {
    driver: &'driver mut DbDriver,
    query: Query,
    _record: PhantomData<Record>,
}

impl<'driver, Query, Record> PendingStatement<'driver, Query, Record> {
    /// Builds a pending statement from an already-built query.
    pub fn new(driver: &'driver mut DbDriver, query: Query) -> Self {
        Self {
            driver,
            query,
            _record: PhantomData,
        }
    }

    /// Rebuilds the captured query while keeping the captured driver.
    pub fn build<NextQuery>(
        self,
        build: impl FnOnce(Query) -> NextQuery,
    ) -> PendingStatement<'driver, NextQuery, Record> {
        PendingStatement {
            driver: self.driver,
            query: build(self.query),
            _record: PhantomData,
        }
    }
}

impl<'driver, Query, Record> PendingStatement<'driver, Query, Record>
where
    Record: DbRecord,
{
    /// Applies a filter while keeping the captured driver.
    pub fn filter<Predicate>(
        self,
        filter: impl FnOnce(Record::Columns) -> Predicate,
    ) -> PendingStatement<'driver, <Query as FilterDsl<Predicate>>::Output, Record>
    where
        Query: FilterDsl<Predicate>,
    {
        let predicate = filter(Record::columns());

        PendingStatement {
            driver: self.driver,
            query: self.query.filter(predicate),
            _record: PhantomData,
        }
    }

    /// Applies an order clause while keeping the captured driver.
    pub fn order<Order>(
        self,
        order: impl FnOnce(Record::Columns) -> Order,
    ) -> PendingStatement<'driver, <Query as OrderDsl<Order>>::Output, Record>
    where
        Query: OrderDsl<Order>,
        Order: Expression,
    {
        let order = order(Record::columns());

        PendingStatement {
            driver: self.driver,
            query: self.query.order(order),
            _record: PhantomData,
        }
    }
}

impl<Query, Record> PendingStatement<'_, Query, Record>
where
    Query: ExecuteDsl<DbDriver>,
{
    /// Executes the captured statement and returns the affected row count.
    pub fn execute(self) -> Result<usize> {
        ExecuteDsl::execute(self.query, self.driver).map_err(anyhow::Error::from)
    }
}

impl<'driver, Query, Record> PendingStatement<'driver, Query, Record> {
    /// Loads rows from the captured query.
    pub fn load<Row>(self) -> Result<Vec<Row>>
    where
        Query: LoadQuery<'driver, DbDriver, Row>,
    {
        self.query
            .load::<Row>(self.driver)
            .map_err(anyhow::Error::from)
    }
}

/// Pending insert created by [`DbDriver::insert`](crate::connection::DbDriver::insert).
pub struct PendingInsert<'driver, Record>
where
    Record: HasTable,
{
    driver: &'driver mut DbDriver,
    record: Record,
}

impl<'driver, Record> PendingInsert<'driver, Record>
where
    Record: HasTable,
{
    /// Builds a pending insert from an already-prepared record.
    pub fn new(driver: &'driver mut DbDriver, record: Record) -> Self {
        Self { driver, record }
    }
}

impl<Record> PendingInsert<'_, Record>
where
    Record: HasTable + Insertable<<Record as HasTable>::Table>,
    <Record as HasTable>::Table: QueryId + 'static,
    <<Record as HasTable>::Table as diesel::query_source::QuerySource>::FromClause:
        QueryFragment<<DbDriver as Connection>::Backend>,
    <Record as Insertable<<Record as HasTable>::Table>>::Values: QueryFragment<<DbDriver as Connection>::Backend>
        + CanInsertInSingleQuery<<DbDriver as Connection>::Backend>
        + QueryId,
{
    /// Executes the inferred insert against the captured driver.
    pub fn execute(self) -> Result<usize> {
        diesel::insert_into(Record::table())
            .values(self.record)
            .execute(self.driver)
            .map_err(anyhow::Error::from)
    }
}
