//! Traits for exposing Bevy components to Lua scripts.
//!
//! [`LuaComponent`] is the bridge: implement it (or derive with `#[derive(LuaComponent)]`)
//! and the component becomes readable and writable from Lua by name.

use bevy::prelude::*;
use serde::{Serialize, de::DeserializeOwned};
use serde_json::Value as Json;

use crate::runtime::ComponentAccessor;

/// Implemented by components that can be read and written from Lua scripts.
///
/// Use `#[derive(LuaComponent)]` from `suon_macros`. The derive also generates
/// the [`bevy::prelude::Component`] impl, so you should not derive `Component`
/// alongside it. Registration in [`crate::runtime::ScriptRegistry`] happens automatically
/// the first time the component is inserted into any entity.
///
/// ```ignore
/// #[derive(LuaComponent, Serialize, Deserialize)]
/// struct Health { value: i32 }
/// ```
///
/// > **Note:** Manual implementations must register the component in
/// > [`crate::ScriptRegistry`] themselves, or call [`AppLuaExt::register_lua_component`]
/// > explicitly — the `on_add` hook generated by `#[derive(LuaComponent)]` does this
/// > automatically on first insert.
pub trait LuaComponent: Component {
    /// Returns the component name exposed to Lua scripts, such as `"Health"`.
    fn lua_name() -> &'static str;

    /// Builds the [`ComponentAccessor`] used by the Lua runtime to read and write this component.
    fn make_accessor() -> ComponentAccessor;
}

/// Extension methods for serialising and deserialising ECS components directly on [`World`].
pub trait WorldLuaComponentExt {
    /// Serialises component `T` on `entity` to a [`serde_json::Value`].
    ///
    /// Returns `None` when the entity does not have the component or when
    /// serialisation fails.
    fn serialize_lua_component<T>(&mut self, entity: Entity) -> Option<Json>
    where
        T: Component + Serialize;

    /// Deserialises `json` and inserts or replaces component `T` on `entity`.
    ///
    /// Invalid JSON is ignored so the existing component stays unchanged.
    fn deserialize_lua_component<T>(&mut self, entity: Entity, json: Json)
    where
        T: Component + DeserializeOwned;
}

impl WorldLuaComponentExt for World {
    fn serialize_lua_component<T>(&mut self, entity: Entity) -> Option<Json>
    where
        T: Component + Serialize,
    {
        let component_ref = self.get::<T>(entity)?;
        serde_json::to_value(component_ref).ok()
    }

    fn deserialize_lua_component<T>(&mut self, entity: Entity, json: Json)
    where
        T: Component + DeserializeOwned,
    {
        if let Ok(deserialized_component) = serde_json::from_value::<T>(json) {
            self.entity_mut(entity).insert(deserialized_component);
        }
    }
}

/// Extension trait that lets [`App`] register a [`LuaComponent`] with one call.
pub trait AppLuaExt {
    /// Registers `T` in the [`crate::runtime::ScriptRegistry`] under its [`LuaComponent::lua_name`].
    ///
    /// Use this when you need the component accessible from Lua before the first
    /// entity with that component is spawned. Otherwise the automatic `on_add` hook
    /// generated by `#[derive(LuaComponent)]` handles registration on first insert.
    fn register_lua_component<T: LuaComponent>(&mut self) -> &mut Self;
}

impl AppLuaExt for App {
    fn register_lua_component<T: LuaComponent>(&mut self) -> &mut Self {
        self.world_mut()
            .resource_mut::<crate::runtime::ScriptRegistry>()
            .register_component(T::lua_name(), T::make_accessor());
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime::{LuaRuntime, ScriptRegistry};
    use serde::{Deserialize, Serialize};
    use suon_macros::LuaComponent;

    #[derive(LuaComponent, Serialize, Deserialize)]
    struct Gold {
        amount: i32,
    }

    #[test]
    fn serialize_component_serializes_to_json() {
        let mut world = World::new();
        world.init_resource::<ScriptRegistry>();

        let entity = world.spawn(Gold { amount: 42 }).id();

        let json = world
            .serialize_lua_component::<Gold>(entity)
            .expect("Gold should be present on entity");

        assert_eq!(json["amount"], serde_json::json!(42));
    }

    #[test]
    fn serialize_component_returns_none_when_component_absent() {
        let mut world = World::new();

        let entity = world.spawn_empty().id();

        assert!(world.serialize_lua_component::<Gold>(entity).is_none());
    }

    #[test]
    fn deserialize_component_inserts_deserialized_component() {
        let mut world = World::new();
        world.init_resource::<ScriptRegistry>();

        let entity = world.spawn_empty().id();

        world.deserialize_lua_component::<Gold>(entity, serde_json::json!({ "amount": 99 }));

        assert_eq!(
            world
                .get::<Gold>(entity)
                .expect("Gold should be present")
                .amount,
            99
        );
    }

    #[test]
    fn deserialize_component_updates_existing_component() {
        let mut world = World::new();
        world.init_resource::<ScriptRegistry>();

        let entity = world.spawn(Gold { amount: 1 }).id();

        world.deserialize_lua_component::<Gold>(entity, serde_json::json!({ "amount": 50 }));

        assert_eq!(
            world
                .get::<Gold>(entity)
                .expect("Gold should be present")
                .amount,
            50
        );
    }

    #[test]
    fn deserialize_component_ignores_malformed_json() {
        let mut world = World::new();
        world.init_resource::<ScriptRegistry>();

        let entity = world.spawn(Gold { amount: 7 }).id();

        world.deserialize_lua_component::<Gold>(entity, serde_json::json!("not an object"));

        assert_eq!(
            world
                .get::<Gold>(entity)
                .expect("Gold should be present")
                .amount,
            7
        );
    }

    #[test]
    fn lua_name_is_correct() {
        assert_eq!(Gold::lua_name(), "Gold");
    }

    #[test]
    fn make_accessor_get_works_via_lua() {
        let runtime = LuaRuntime::new();

        let mut world = World::new();
        world.init_resource::<ScriptRegistry>();

        world.spawn(Gold { amount: 10 });

        runtime
            .scope(&mut world)
            .execute(
                "
            for id, gold in Query(Gold):iter() do
                assert(gold.amount == 10, 'expected 10, got ' .. tostring(gold.amount))
            end
        ",
            )
            .expect("lua exec should succeed");
    }

    #[test]
    fn make_accessor_write_via_proxy_works() {
        let runtime = LuaRuntime::new();

        let mut world = World::new();
        world.init_resource::<ScriptRegistry>();

        let entity = world.spawn(Gold { amount: 0 }).id();

        runtime
            .scope(&mut world)
            .execute(&format!(
                "
            local entity = Entity({})
            local gold = entity:get(Gold)
            gold.amount = 77
        ",
                entity.to_bits()
            ))
            .expect("lua exec should succeed");

        assert_eq!(
            world
                .get::<Gold>(entity)
                .expect("Gold should be present")
                .amount,
            77
        );
    }

    #[test]
    fn app_register_lua_component_adds_to_registry() {
        let mut app = App::new();
        app.init_resource::<ScriptRegistry>();
        app.register_lua_component::<Gold>();

        assert!(
            app.world()
                .resource::<ScriptRegistry>()
                .components
                .contains_key("Gold")
        );
    }

    #[test]
    fn serialize_component_returns_none_for_despawned_entity() {
        let mut world = World::new();
        world.init_resource::<ScriptRegistry>();

        let entity = world.spawn(Gold { amount: 5 }).id();

        world.despawn(entity);

        assert!(world.serialize_lua_component::<Gold>(entity).is_none());
    }

    #[test]
    fn deserialize_component_with_null_json_does_not_insert_component() {
        let mut world = World::new();
        world.init_resource::<ScriptRegistry>();

        let entity = world.spawn_empty().id();

        world.deserialize_lua_component::<Gold>(entity, serde_json::Value::Null);

        assert!(world.get::<Gold>(entity).is_none());
    }

    #[test]
    fn component_roundtrip_via_get_then_set() {
        let mut world = World::new();
        world.init_resource::<ScriptRegistry>();

        let entity = world.spawn(Gold { amount: 33 }).id();

        let json = world
            .serialize_lua_component::<Gold>(entity)
            .expect("should serialize");

        world.deserialize_lua_component::<Gold>(entity, json);

        assert_eq!(
            world
                .get::<Gold>(entity)
                .expect("Gold should be present after deserialize_lua_component")
                .amount,
            33
        );
    }

    #[test]
    fn deserialize_component_is_atomic_when_field_type_mismatches() {
        let mut world = World::new();
        world.init_resource::<ScriptRegistry>();

        let entity = world.spawn(Gold { amount: 7 }).id();

        world.deserialize_lua_component::<Gold>(
            entity,
            serde_json::json!({ "amount": "not_a_number" }),
        );

        assert_eq!(
            world
                .get::<Gold>(entity)
                .expect("Gold should still be present")
                .amount,
            7,
            "component should be unchanged after a type-mismatch deserialization failure"
        );
    }

    #[test]
    fn serialize_component_serializes_enum_field() {
        #[derive(Serialize, Deserialize, PartialEq, Debug)]
        enum Stance {
            Idle,
            Combat,
        }

        #[derive(Component, Serialize, Deserialize)]
        struct Fighter {
            stance: Stance,
        }

        let mut world = World::new();
        world.init_resource::<ScriptRegistry>();

        let entity = world
            .spawn(Fighter {
                stance: Stance::Combat,
            })
            .id();

        let json = world
            .serialize_lua_component::<Fighter>(entity)
            .expect("Fighter should serialize");

        assert_eq!(
            json["stance"],
            serde_json::json!("Combat"),
            "enum variant should be serialized as its name string"
        );
    }

    #[test]
    fn json_with_duplicate_keys_last_value_wins() {
        let json: serde_json::Value = serde_json::from_str(r#"{"amount": 1, "amount": 99}"#)
            .expect("duplicate-key JSON should parse");

        let mut world = World::new();
        world.init_resource::<ScriptRegistry>();

        let entity = world.spawn(Gold { amount: 0 }).id();
        world.deserialize_lua_component::<Gold>(entity, json);

        assert_eq!(
            world
                .get::<Gold>(entity)
                .expect("Gold should be present")
                .amount,
            99,
            "last occurrence of a duplicate key should win"
        );
    }

    #[test]
    fn app_register_lua_component_is_callable_from_lua() {
        let runtime = LuaRuntime::new();

        let mut app = App::new();
        app.init_resource::<ScriptRegistry>();
        app.register_lua_component::<Gold>();

        let entity = app.world_mut().spawn(Gold { amount: 5 }).id();

        runtime
            .scope(app.world_mut())
            .execute(&format!(
                "
            local entity = Entity({})
            local gold = entity:get(Gold)
            assert(gold ~= nil)
            assert(gold.amount == 5)
        ",
                entity.to_bits()
            ))
            .expect("lua exec should succeed");
    }
}
