//! Trait and helpers for exposing Bevy components to Lua scripts.
//!
//! [`LuaComponent`] is the bridge: implement it (or derive with `#[derive(LuaComponent)]`)
//! and the component becomes readable/writable from Lua by name.

use bevy::{ecs::component::ComponentId, prelude::*};
use serde::{Serialize, de::DeserializeOwned};
use serde_json::Value as Json;

use crate::runtime::ComponentAccessor;

/// Implemented by components that can be read and written from Lua scripts.
///
/// Use `#[derive(LuaComponent)]` from `suon_macros`. The derive also generates
/// the [`bevy::prelude::Component`] impl — do **not** use `#[derive(Component)]`
/// alongside it. Registration in [`crate::runtime::ScriptRegistry`] happens automatically the
/// first time the component is inserted into any entity.
///
/// ```ignore
/// #[derive(LuaComponent, Serialize, Deserialize)]
/// struct Health { value: i32 }
/// ```
///
/// # Safety
///
/// The `on_add` hook generated by `#[derive(LuaComponent)]` registers the component in
/// [`crate::ScriptRegistry`] on first insert. If you implement this trait manually you **must**
/// provide an equivalent hook, otherwise the component will not be reachable from Lua
/// unless you call [`AppLuaExt::register_lua_component`] explicitly.
pub trait LuaComponent: Component {
    /// The name exposed to Lua scripts — e.g. `"Health"`.
    fn lua_name() -> &'static str;

    /// Constructs a [`ComponentAccessor`] wired to this type's serde impls.
    fn make_accessor() -> ComponentAccessor;
}

/// Serialises the component `T` on `entity` to a [`serde_json::Value`].
///
/// Returns `None` when the entity does not have the component.
///
/// # Errors
///
/// Returns `None` (not an error) on serialisation failure — this mirrors the
/// convention used across the accessor vtable.
pub fn serialize_component<T>(entity: Entity, world: &mut World) -> Option<Json>
where
    T: Component + Serialize,
{
    let component = world.get::<T>(entity)?;
    serde_json::to_value(component).ok()
}

/// Deserialises `json` and inserts or replaces component `T` on `entity`.
///
/// Silently ignores JSON that cannot be deserialised into `T` — the component
/// is left unchanged rather than partially written.
pub fn deserialize_component<T>(entity: Entity, world: &mut World, json: Json)
where
    T: Component + DeserializeOwned,
{
    if let Ok(component) = serde_json::from_value::<T>(json) {
        world.entity_mut(entity).insert(component);
    }
}

/// Registers component `T` with the world (if not already registered) and returns its [`ComponentId`].
///
/// Calling this multiple times for the same `T` is safe — the id is stable.
pub fn register_component_id<T: Component>(world: &mut World) -> ComponentId {
    world.register_component::<T>()
}

/// Extension trait that lets `App` register a [`LuaComponent`] with one call.
pub trait AppLuaExt {
    /// Registers `T` in the [`crate::runtime::ScriptRegistry`] under its [`LuaComponent::lua_name`].
    ///
    /// Use this when you need the component accessible from Lua **before** the first
    /// entity with that component is spawned. Otherwise the automatic `on_add` hook
    /// (generated by `#[derive(LuaComponent)]`) handles registration on first insert.
    fn register_lua_component<T: LuaComponent>(&mut self) -> &mut Self;
}

impl AppLuaExt for App {
    fn register_lua_component<T: LuaComponent>(&mut self) -> &mut Self {
        self.world_mut()
            .resource_mut::<crate::runtime::ScriptRegistry>()
            .register_component(T::lua_name(), T::make_accessor());
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime::{LuaRuntime, ScriptRegistry};
    use serde::{Deserialize, Serialize};

    #[derive(Component, Serialize, Deserialize)]
    struct Gold {
        amount: i32,
    }

    impl LuaComponent for Gold {
        fn lua_name() -> &'static str {
            "Gold"
        }

        fn make_accessor() -> ComponentAccessor {
            ComponentAccessor {
                get: serialize_component::<Gold>,
                set: deserialize_component::<Gold>,
                component_id: register_component_id::<Gold>,
            }
        }
    }

    fn setup() -> (LuaRuntime, World) {
        let mut world = World::new();
        world.init_resource::<ScriptRegistry>();
        world
            .resource_mut::<ScriptRegistry>()
            .register_component(Gold::lua_name(), Gold::make_accessor());
        (LuaRuntime::new(), world)
    }

    fn run(runtime: &LuaRuntime, world: &mut World, lua: &str) {
        runtime
            .scope(world)
            .execute(lua)
            .expect("lua exec should succeed");
    }

    #[test]
    fn serialize_component_serializes_to_json() {
        let mut world = World::new();
        let entity = world.spawn(Gold { amount: 42 }).id();
        let json = serialize_component::<Gold>(entity, &mut world)
            .expect("Gold should be present on entity");
        assert_eq!(json["amount"], serde_json::json!(42));
    }

    #[test]
    fn serialize_component_returns_none_when_component_absent() {
        let mut world = World::new();
        let entity = world.spawn_empty().id();
        assert!(serialize_component::<Gold>(entity, &mut world).is_none());
    }

    #[test]
    fn deserialize_component_inserts_deserialized_component() {
        let mut world = World::new();
        let entity = world.spawn_empty().id();
        deserialize_component::<Gold>(entity, &mut world, serde_json::json!({ "amount": 99 }));
        assert_eq!(
            world
                .get::<Gold>(entity)
                .expect("Gold should be present")
                .amount,
            99
        );
    }

    #[test]
    fn deserialize_component_updates_existing_component() {
        let mut world = World::new();
        let entity = world.spawn(Gold { amount: 1 }).id();
        deserialize_component::<Gold>(entity, &mut world, serde_json::json!({ "amount": 50 }));
        assert_eq!(
            world
                .get::<Gold>(entity)
                .expect("Gold should be present")
                .amount,
            50
        );
    }

    #[test]
    fn deserialize_component_ignores_malformed_json() {
        let mut world = World::new();
        let entity = world.spawn(Gold { amount: 7 }).id();
        deserialize_component::<Gold>(entity, &mut world, serde_json::json!("not an object"));
        assert_eq!(
            world
                .get::<Gold>(entity)
                .expect("Gold should be present")
                .amount,
            7
        );
    }

    #[test]
    fn register_component_id_returns_stable_id() {
        let mut world = World::new();
        let first = register_component_id::<Gold>(&mut world);
        let second = register_component_id::<Gold>(&mut world);
        assert_eq!(first, second);
    }

    #[test]
    fn lua_name_is_correct() {
        assert_eq!(Gold::lua_name(), "Gold");
    }

    #[test]
    fn make_accessor_get_works_via_lua() {
        let (runtime, mut world) = setup();
        world.spawn(Gold { amount: 10 });

        run(
            &runtime,
            &mut world,
            "
            for id, gold in Query('Gold'):iter() do
                assert(gold.amount == 10, 'expected 10, got ' .. tostring(gold.amount))
            end
        ",
        );
    }

    #[test]
    fn make_accessor_set_works_via_lua() {
        let (runtime, mut world) = setup();
        let entity = world.spawn(Gold { amount: 0 }).id();

        run(
            &runtime,
            &mut world,
            &format!(
                "
            local entity = Entity({})
            entity:set('Gold', {{ amount = 77 }})
        ",
                entity.to_bits()
            ),
        );

        assert_eq!(
            world
                .get::<Gold>(entity)
                .expect("Gold should be present")
                .amount,
            77
        );
    }

    #[test]
    fn app_register_lua_component_adds_to_registry() {
        let mut app = App::new();
        app.init_resource::<ScriptRegistry>();
        app.register_lua_component::<Gold>();
        assert!(
            app.world()
                .resource::<ScriptRegistry>()
                .components
                .contains_key("Gold")
        );
    }

    #[test]
    fn serialize_component_returns_none_for_despawned_entity() {
        let mut world = World::new();
        let entity = world.spawn(Gold { amount: 5 }).id();
        world.despawn(entity);
        assert!(serialize_component::<Gold>(entity, &mut world).is_none());
    }

    #[test]
    fn deserialize_component_with_null_json_does_not_insert_component() {
        let mut world = World::new();
        let entity = world.spawn_empty().id();
        deserialize_component::<Gold>(entity, &mut world, serde_json::Value::Null);
        assert!(world.get::<Gold>(entity).is_none());
    }

    #[test]
    fn component_roundtrip_via_get_then_set() {
        let mut world = World::new();
        let entity = world.spawn(Gold { amount: 33 }).id();
        let json = serialize_component::<Gold>(entity, &mut world).expect("should serialize");
        deserialize_component::<Gold>(entity, &mut world, json);
        assert_eq!(world.get::<Gold>(entity).unwrap().amount, 33);
    }

    #[test]
    fn deserialize_component_is_atomic_when_field_type_mismatches() {
        // `amount` expects i32; passing a string causes serde_json::from_value to fail
        // atomically, so the component must remain unchanged.
        let mut world = World::new();
        let entity = world.spawn(Gold { amount: 7 }).id();
        deserialize_component::<Gold>(
            entity,
            &mut world,
            serde_json::json!({ "amount": "not_a_number" }),
        );
        assert_eq!(
            world
                .get::<Gold>(entity)
                .expect("Gold should still be present")
                .amount,
            7,
            "component should be unchanged after a type-mismatch deserialization failure"
        );
    }

    #[test]
    fn serialize_component_serializes_enum_field() {
        #[derive(Serialize, Deserialize, PartialEq, Debug)]
        enum Stance {
            Idle,
            Combat,
        }

        #[derive(Component, Serialize, Deserialize)]
        struct Fighter {
            stance: Stance,
        }

        let mut world = World::new();
        let entity = world
            .spawn(Fighter {
                stance: Stance::Combat,
            })
            .id();
        let json =
            serialize_component::<Fighter>(entity, &mut world).expect("Fighter should serialize");
        assert_eq!(
            json["stance"],
            serde_json::json!("Combat"),
            "enum variant should be serialized as its name string"
        );
    }

    #[test]
    fn json_with_duplicate_keys_last_value_wins() {
        // serde_json's default behavior: last occurrence of a duplicate key wins.
        // Verify that deserialize_component handles this without panicking and produces
        // a valid component.
        let json: serde_json::Value =
            serde_json::from_str(r#"{"amount": 1, "amount": 99}"#).unwrap();
        let mut world = World::new();
        let entity = world.spawn(Gold { amount: 0 }).id();
        deserialize_component::<Gold>(entity, &mut world, json);
        assert_eq!(
            world
                .get::<Gold>(entity)
                .expect("Gold should be present")
                .amount,
            99,
            "last occurrence of a duplicate key should win"
        );
    }

    #[test]
    fn app_register_lua_component_is_callable_from_lua() {
        let mut app = App::new();
        app.init_resource::<ScriptRegistry>();
        app.register_lua_component::<Gold>();

        let entity = app.world_mut().spawn(Gold { amount: 5 }).id();
        let runtime = LuaRuntime::new();

        runtime
            .scope(app.world_mut())
            .execute(&format!(
                "
            local entity = Entity({})
            local gold = entity:get('Gold')
            assert(gold ~= nil)
            assert(gold.amount == 5)
        ",
                entity.to_bits()
            ))
            .expect("lua exec should succeed");
    }
}
