[alias]
build-artifacts = "run -p build -- build-artifacts"

[target.x86_64-unknown-linux-gnu]
rustflags = [
	# Mold linker
	# You may need to install it first.
	# "-Clink-arg=-fuse-ld=mold",

	# Nightly
	# "-Zshare-generics=y",
	# "-Zthreads=0",
]

rustdocflags = [
	# Mold linker
	# "-Clink-arg=-fuse-ld=mold",
]

[target.x86_64-apple-darwin]
rustflags = [
	# LLD linker
	# The default ld64 linker is often faster on macOS, so this stays disabled.
	# "-Clink-arg=-fuse-ld=/usr/local/opt/llvm/bin/ld64.lld",

	# Nightly
	# "-Zshare-generics=y",
	# "-Zthreads=0",
]

[target.aarch64-apple-darwin]
rustflags = [
	# LLD linker
	# The default ld64 linker is often faster on macOS, so this stays disabled.
	# "-Clink-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld",

	# Nightly
	# "-Zshare-generics=y",
	# "-Zthreads=0",
]

[target.x86_64-pc-windows-msvc]
# LLD linker
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
rustflags = [
	# Nightly
	"-Zshare-generics=n",
	"-Zthreads=0",
]

# Optional:
# [profile.dev]
# debug = 1
